version: '3'

services:
  app:
    build: .
    ports:
      - "8081:8081"
#    depends_on:
##      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

#  postgres-database:
#    image: 'postgres:15-alpine'
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin-password