info:
  application:
    name: expense-tracker
    description: Srping Boot Expense Tracker Application
    author: Ibrahim Kesici

server:
  servlet:
    context-path: /api/v1
  port: 8081

spring:
  profiles:
    active: dev
